{
    "coord": {
        "lon": -121.9406,
        "lat": 37.4087
    },
    "weather": [
        {
            "id": 711,
            "main": "Smoke",
            "description": "smoke",
            "icon": "50d"
        }
    ],
    "base": "stations",
    "main": {
        "temp": 58.6,
        "feels_like": 58.26,
        "temp_min": 53.38,
        "temp_max": 62.56,
        "pressure": 1016,
        "humidity": 87
    },
    "visibility": 10000,
    "wind": {
        "speed": 3.44,
        "deg": 100
    },
    "clouds": {
        "all": 75
    },
    "dt": 1628258755,
    "sys": {
        "type": 1,
        "id": 5845,
        "country": "US",
        "sunrise": 1628255795,
        "sunset": 1628305839
    },
    "timezone": -25200,
    "id": 0,
    "name": "San Jose",
    "cod": 200
}